### ISSUE TITLE
webpack-dev-server - 1.14.1 throws error, Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ghost** [rundis/albums#3]
I am not sure, if the frontend code is working for all. When i tried to run `npm run dev` after doing npm install, it throws an error,
`TypeError: Cannot read property 'replace' of undefined`

I see, people are discussing it [https://github.com/webpack/webpack-dev-server/issues/367](url)

So, I too tried to move to webpack-dev-server==1.14.0 & did, `rm -rf node_moduels/  && npm install`. Still, the error remains. I use nodejs versioned 6.2.2 & npm versioned 3.9.5

**Comment by liiklin** [comment]
maybe forgot post webpack.config.js file.

**Comment by liiklin** [comment]
create new webpack.config.js in the root of fronrend .
copy this page js to webpack.config.js file.

[webpack.config.js](https://github.com/fluxxu/elm-hot-loader-starter/blob/master/webpack.config.js)

**Comment by rundis** [comment]
Tx for the report and of course the problem is an overzealous .gitignore. Apologies.
